version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  cockroach:
    image: cockroachdb/cockroach-unstable:v21.2.0-beta.4
    command: start-single-node --insecure --listen-addr=0.0.0.0:26257

  jupyter:
    build: ./jupyter
    ports:
      - 8888:8888
    volumes:
      - ./jupyter/notebooks:/home/jovyan/notebooks
